### ISSUE TITLE
放在子目录也可以用是吧

### ISSUE THREAD

**Issue by bbhxwl** [SpringHgui/VueRouterHistory#1]
放在子目录也可以用是吧

**Comment by SpringHgui** [comment]
可以的，源码中的例子包含了放到子目录的情况

**Comment by bbhxwl** [comment]
> 可以的，源码中的例子包含了放到子目录的情况

666,晚点我试试，正为这个模式不能放到子目录愁，现在部署的不同域名，但是不同域名用token又会预加载api接口，麻烦。

**Comment by SpringHgui** [comment]
`vuerouter`的`base_url`也同样设置为相对于你的域名的子路径，一般来说不管什么需求，改改中间件逻辑都能实现，如果解决不了再提issue
