### ISSUE TITLE
.net 5配置后还是404

### ISSUE THREAD

**Issue by onesmail** [SpringHgui/VueRouterHistory#2]
您好，我用的是.net 5，按照您的博客配置，访问后还是404，下载您github上的Demo发布后运行也没有问题，我的就是不行，实在是找不到原因了，求助。😢
![image](https://user-images.githubusercontent.com/9582449/186553228-78418222-18b6-4a47-b011-baf0dc4be57b.png)

**Comment by SpringHgui** [comment]
去掉 `app.UseDefalutFiles()` 试下

**Comment by onesmail** [comment]
> 

试了，还是不行，还会是什么原因呢？

**Comment by SpringHgui** [comment]
提供个最小复现该问题的demo地址或压缩包，我看下

**Comment by onesmail** [comment]
> 提供个最小复现该问题的demo地址或压缩包，我看下

我发布后的vue文件放到您demo的wwwroot下面不行，放入您发布后的vue文件就可以，怀疑可能是前端vue的配置问题，下面是我的vue路由配置，用的是vue2，您看看有没有其他要注意的
![微信截图_20220825103516](https://user-images.githubusercontent.com/9582449/186561417-3da6559a-0eac-496e-ae91-42648f16a0d8.png)

**Comment by SpringHgui** [comment]
那应该是vueRouter的base与wwwroot层级结构不匹配





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月25日(星期四) 上午10:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SpringHgui/VueRouterHistory] .net 5配置后还是404 (Issue #2)





  
提供个最小复现该问题的demo地址或压缩包，我看下
  
我发布后的vue文件放到您demo的wwwroot下面不行，放入您发布后的vue文件就可以，怀疑可能是前端vue的配置问题，下面是我的vue路由配置，用的是vue2，您看看有没有其他要注意的
 
 
&mdash;

**Comment by SpringHgui** [comment]
![image](https://user-images.githubusercontent.com/22363718/186564438-45fdfbd6-ca71-49b3-91e4-69004f33ea17.png)
比如你页面放在`wwwroot/test1`文件夹下面，则应该为
```js
const router = new VueRouter({
    mode: "history",
    base: "/test1"
})
```

**Comment by onesmail** [comment]
> ![image](https://user-images.githubusercontent.com/22363718/186564438-45fdfbd6-ca71-49b3-91e4-69004f33ea17.png) 比如你页面放在`wwwroot/test1`文件夹下面，则应该为
> 
> ```js
> const router = new VueRouter({
>     mode: "history",
>     base: "/test1"
> })
> ```

前端能解决这种问题吗？

**Comment by SpringHgui** [comment]
解决什么问题，history模式？ 

不行，history必须后端支持

**Comment by onesmail** [comment]
> 解决什么问题，history模式？
> 
> 不行，history必须后端支持

那就是前端vue页面如果放在子目录，不在根目录，vue发布后放到wwwroot用history是找不到页面的，那就不能用history，只能用hash模式了吗？base与wwwroot层级结构不匹配的问题没有解决方案呢？

**Comment by SpringHgui** [comment]
没看到上面说的吗？
配置`vue-router`的`base`参数，本项目源码代码中也有非根目录的结构，你说的404是vuerouter找不到页面吧，而不是后端找不到页面

> ![image](https://user-images.githubusercontent.com/22363718/186564438-45fdfbd6-ca71-49b3-91e4-69004f33ea17.png) 比如你页面放在`wwwroot/test1`文件夹下面，则应该为
> 
> ```js
> const router = new VueRouter({
>     mode: "history",
>     base: "/test1"
> })
> ```

**Comment by onesmail** [comment]
> 没看到上面说的吗？ 配置`vue-router`的`base`参数，本项目源码代码中也有非根目录的结构，你说的404是vuerouter找不到页面吧，而不是后端找不到页面
> 
> > ![image](https://user-images.githubusercontent.com/22363718/186564438-45fdfbd6-ca71-49b3-91e4-69004f33ea17.png) 比如你页面放在`wwwroot/test1`文件夹下面，则应该为
> > ```js
> > const router = new VueRouter({
> >     mode: "history",
> >     base: "/test1"
> > })
> > ```

不好意思，麻烦了，我明白你的意思，webroot下面嵌套多个index.html要配置/test1，我发布的只有1个index.html
![微信截图_20220825121044](https://user-images.githubusercontent.com/9582449/186572998-23c0870f-d83b-4e74-8263-b820f007636c.png)

给你您的demo里面新加一个vue页面，只不过是放在admin下，发布后也是访问不到的
![1](https://user-images.githubusercontent.com/9582449/186573603-aa137be7-e01a-4ae1-9fb2-e97dfcbc6223.png)
![2](https://user-images.githubusercontent.com/9582449/186573645-ebacb840-a8b2-488d-bc1c-e2e6d2d6a6a8.png)

**Comment by SpringHgui** [comment]
给一个最小复现的demo吧

**Comment by onesmail** [comment]
> 给一个最小复现的demo吧

这个是在您的测试代码上修改的，vue项目views多加一个admin目录，下面放了一个index.vue
[测试demo](https://wws.lanzoum.com/iLfRj0a8crqj)

**Comment by SpringHgui** [comment]
你`vuerouter`加对应页面的路由了吗

**Comment by onesmail** [comment]
> 你`vuerouter`加对应页面的路由了吗

都加了，你看看，这是一部分截图，不刷新页面可以正常访问，刷新就404
![codePng (1)](https://user-images.githubusercontent.com/9582449/186611671-ca683226-e21c-4e70-b202-60337ea50d89.png)

**Comment by junsk1227** [comment]
你好，在测试过程中遇到一个问题：输入不存在的地址时，vue-router配置不能生效，无法重定向到404页面。
vue-router4.x配置如下：
`
const constanRoutes = [
     .....,
    {
        path: "/:pathMatch(.*)*",
        component: () => import('@/views/error/404.vue'),
        hidden: true
    }
]
const router = createRouter({
    history: createWebHistory(),
    routes: constantRoutes
});
`
