### ISSUE TITLE
刷新浏览器后，请求资源url错误404

### ISSUE THREAD

**Issue by iarthit** [SpringHgui/VueRouterHistory#4]
请教一个作者问题，
当我刷新页面的时候，如果页面地址url为：http://localhost:5000/aaa/bbb，那么请求页面资源就变了：http://localhost:5000/aaa/assets/js/index-c5d2eb2d.js，这是为啥呢？

如果页面地址为：http://localhost:5000/aaa，那么请求页面资源就正常：http://localhost:5000/assets/js/index-c5d2eb2d.js，前端是哪里需要修改吗？

**Comment by SpringHgui** [comment]
提供一个复现的demo仓库地址吧

**Comment by iarthit** [comment]
找到问题所在了，vite.config.ts中的 base应该写成 "/"，而不是  "./"，不好意思
